[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"
authors = ["Andres Suarez <andres.vsm1@gmail.com>"]
description = "API using actix framework"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"